export type FarmCropCategoryId = "common" | "fantasy" | "limited";
export type FarmCropRarity = "N" | "R" | "SR" | "SSR" | "SP";

export interface FarmCropCatalogEntry {
  id: string;
  name: string;
  category: FarmCropCategoryId;
  rarity: FarmCropRarity;
}

export const FARM_CROP_CATEGORIES = [
  { id: "common", label: "普通" },
  { id: "fantasy", label: "奇幻" },
  { id: "limited", label: "限定" },
] as const satisfies readonly { id: FarmCropCategoryId; label: string }[];

export const FARM_CROP_RARITY_ORDER = {
  N: 0,
  R: 1,
  SR: 2,
  SSR: 3,
  SP: 4,
} as const satisfies Record<FarmCropRarity, number>;

export const FARM_CROP_CATALOG = [
  { id: "wheat", name: "小麦", category: "common", rarity: "N" },
  { id: "corn", name: "玉米", category: "common", rarity: "N" },
  { id: "carrot", name: "胡萝卜", category: "common", rarity: "N" },
  { id: "potato", name: "马铃薯", category: "common", rarity: "N" },
  { id: "cabbage", name: "卷心菜", category: "common", rarity: "N" },
  { id: "onion", name: "洋葱", category: "common", rarity: "N" },
  { id: "tomato", name: "番茄", category: "common", rarity: "R" },
  { id: "cucumber", name: "黄瓜", category: "common", rarity: "N" },
  { id: "bell_pepper", name: "甜椒", category: "common", rarity: "R" },
  { id: "eggplant", name: "茄子", category: "common", rarity: "R" },
  { id: "green_bean", name: "四季豆", category: "common", rarity: "N" },
  { id: "radish", name: "萝卜", category: "common", rarity: "N" },
  { id: "spinach", name: "菠菜", category: "common", rarity: "N" },
  { id: "lettuce", name: "生菜", category: "common", rarity: "N" },
  { id: "celery", name: "芹菜", category: "common", rarity: "N" },
  { id: "broccoli", name: "西蓝花", category: "common", rarity: "R" },
  { id: "strawberry", name: "草莓", category: "common", rarity: "R" },
  { id: "pea", name: "豌豆", category: "common", rarity: "N" },
  { id: "asparagus", name: "芦笋", category: "common", rarity: "R" },
  { id: "cauliflower", name: "花椰菜", category: "common", rarity: "SR" },
  { id: "artichoke", name: "洋蓟", category: "common", rarity: "R" },
  { id: "spring_onion", name: "小葱", category: "common", rarity: "N" },
  { id: "watermelon", name: "西瓜", category: "common", rarity: "R" },
  { id: "sunflower", name: "向日葵", category: "common", rarity: "N" },
  { id: "chili", name: "辣椒", category: "common", rarity: "R" },
  { id: "okra", name: "秋葵", category: "common", rarity: "R" },
  { id: "summer_squash", name: "西葫芦", category: "common", rarity: "N" },
  { id: "basil", name: "罗勒", category: "common", rarity: "R" },
  { id: "pumpkin", name: "南瓜", category: "common", rarity: "R" },
  { id: "sweet_potato", name: "红薯", category: "common", rarity: "N" },
  { id: "beet", name: "甜菜", category: "common", rarity: "R" },
  { id: "kale", name: "羽衣甘蓝", category: "common", rarity: "R" },
  { id: "parsnip", name: "欧防风", category: "common", rarity: "SR" },
  { id: "brussels_sprout", name: "抱子甘蓝", category: "common", rarity: "SR" },
  { id: "turnip", name: "芜菁", category: "common", rarity: "N" },
  { id: "leek", name: "韭葱", category: "common", rarity: "N" },
  { id: "winter_wheat", name: "冬小麦", category: "common", rarity: "R" },
  { id: "endive", name: "苦苣", category: "common", rarity: "R" },
  { id: "daikon", name: "白萝卜", category: "common", rarity: "R" },
  { id: "broccoli_rabe", name: "芥兰", category: "common", rarity: "SR" },
  { id: "glow_flower", name: "夜光花", category: "fantasy", rarity: "SR" },
  { id: "echo_bloom", name: "回声花", category: "fantasy", rarity: "SR" },
  { id: "weeping_lily", name: "垂泪百合", category: "fantasy", rarity: "R" },
  { id: "lunar_rose", name: "月相玫瑰", category: "fantasy", rarity: "SSR" },
  { id: "melody_petal", name: "旋律花瓣", category: "fantasy", rarity: "SR" },
  { id: "mirror_orchid", name: "镜面兰", category: "fantasy", rarity: "SSR" },
  { id: "phantom_lotus", name: "幻影莲", category: "fantasy", rarity: "SSR" },
  { id: "ember_tulip", name: "余烬郁金香", category: "fantasy", rarity: "SR" },
  { id: "whisper_crysanth", name: "低语菊", category: "fantasy", rarity: "R" },
  { id: "void_lily", name: "虚空百合", category: "fantasy", rarity: "SSR" },
  { id: "bubble_peony", name: "气泡牡丹", category: "fantasy", rarity: "R" },
  { id: "time_daisy", name: "时光雏菊", category: "fantasy", rarity: "SR" },
  { id: "sunglow_iris", name: "日辉鸢尾", category: "fantasy", rarity: "R" },
  { id: "screaming_mandrake", name: "尖叫曼陀罗", category: "fantasy", rarity: "SSR" },
  { id: "pig_nose_grass", name: "猪鼻草", category: "fantasy", rarity: "R" },
  { id: "tickle_fern", name: "怕痒蕨", category: "fantasy", rarity: "R" },
  { id: "glass_cactus", name: "玻璃仙人掌", category: "fantasy", rarity: "SR" },
  { id: "umbrella_moss", name: "雨伞苔", category: "fantasy", rarity: "R" },
  { id: "mirror_bamboo", name: "镜竹", category: "fantasy", rarity: "SSR" },
  { id: "ink_weed", name: "墨草", category: "fantasy", rarity: "R" },
  { id: "gravity_vine", name: "失重藤", category: "fantasy", rarity: "SR" },
  { id: "clock_thistle", name: "时钟蓟", category: "fantasy", rarity: "SR" },
  { id: "frost_moss", name: "霜衣苔", category: "fantasy", rarity: "SR" },
  { id: "fire_ivy", name: "火藤", category: "fantasy", rarity: "R" },
  { id: "shadow_creeper", name: "影匍藤", category: "fantasy", rarity: "SSR" },
  { id: "spiral_aloe", name: "螺旋芦荟", category: "fantasy", rarity: "SR" },
  { id: "bread_fruit", name: "面包果", category: "fantasy", rarity: "SR" },
  { id: "honey_melon", name: "蜜露瓜", category: "fantasy", rarity: "SR" },
  { id: "butter_bean", name: "黄油豆", category: "fantasy", rarity: "R" },
  { id: "rainbow_corn", name: "彩虹玉米", category: "fantasy", rarity: "SR" },
  { id: "cheese_leaf", name: "奶酪叶", category: "fantasy", rarity: "R" },
  { id: "soda_mushroom", name: "气泡菇", category: "fantasy", rarity: "R" },
  { id: "candy_root", name: "糖果根", category: "fantasy", rarity: "R" },
  { id: "spice_bush", name: "百味灌木", category: "fantasy", rarity: "SR" },
  { id: "chocolate_vine", name: "巧克力藤", category: "fantasy", rarity: "SSR" },
  { id: "cloud_cotton", name: "云棉花", category: "fantasy", rarity: "SR" },
  { id: "pepper_lava", name: "熔岩椒", category: "fantasy", rarity: "SR" },
  { id: "vanilla_orchid", name: "香草兰", category: "fantasy", rarity: "R" },
  { id: "walking_root", name: "行路根", category: "fantasy", rarity: "SR" },
  { id: "shy_tuber", name: "害羞薯", category: "fantasy", rarity: "R" },
  { id: "juggling_vine", name: "杂耍藤", category: "fantasy", rarity: "SR" },
  { id: "guard_shrub", name: "护卫灌木", category: "fantasy", rarity: "SR" },
  { id: "dancing_grass", name: "跳舞草", category: "fantasy", rarity: "R" },
  { id: "huff_puff_shroom", name: "气鼓菇", category: "fantasy", rarity: "R" },
  { id: "migratory_bulb", name: "候鸟鳞茎", category: "fantasy", rarity: "SSR" },
  { id: "fortune_root", name: "占卜根", category: "fantasy", rarity: "SR" },
  { id: "slumber_cabbage", name: "打盹卷心菜", category: "fantasy", rarity: "SR" },
  { id: "crab_weed", name: "螃蟹草", category: "fantasy", rarity: "R" },
  { id: "gobble_melon", name: "贪吃瓜", category: "fantasy", rarity: "SSR" },
  { id: "peekaboo_fern", name: "躲猫猫蕨", category: "fantasy", rarity: "R" },
  { id: "christmas_tree", name: "圣诞树", category: "limited", rarity: "SSR" },
  { id: "pumpkin_lantern", name: "南瓜灯藤", category: "limited", rarity: "SSR" },
  { id: "red_envelope_bamboo", name: "红包竹", category: "limited", rarity: "SSR" },
  { id: "tangyuan_vine", name: "汤圆藤", category: "limited", rarity: "SR" },
  { id: "dragon_boat_reed", name: "龙舟芦苇", category: "limited", rarity: "SR" },
  { id: "mooncake_tree", name: "月饼树", category: "limited", rarity: "SSR" },
  { id: "valentine_rose", name: "情人玫瑰", category: "limited", rarity: "SSR" },
  { id: "easter_eggplant", name: "彩蛋茄", category: "limited", rarity: "SR" },
  { id: "thanks_gourd", name: "感恩葫芦", category: "limited", rarity: "SR" },
  { id: "new_year_bell_flower", name: "新年钟花", category: "limited", rarity: "SSR" },
  { id: "magpie_bridge_vine", name: "鹊桥藤", category: "limited", rarity: "SSR" },
  { id: "childrens_dream_flower", name: "童梦花", category: "limited", rarity: "SR" },
  { id: "collector_wheat", name: "收集者之麦", category: "limited", rarity: "SR" },
  { id: "compendium_orchid", name: "百科兰", category: "limited", rarity: "SSR" },
  { id: "archivist_tree", name: "档案树", category: "limited", rarity: "SSR" },
  { id: "completion_bloom", name: "圆满之花", category: "limited", rarity: "SP" },
  { id: "hermit_moss", name: "隐士苔", category: "limited", rarity: "SR" },
  { id: "witness_root", name: "见证根", category: "limited", rarity: "SSR" },
  { id: "night_owl_cactus", name: "夜猫子仙人掌", category: "limited", rarity: "SSR" },
  { id: "max_land_bloom", name: "满田花", category: "limited", rarity: "SP" },
  { id: "botanist_rose", name: "植物学家玫瑰", category: "limited", rarity: "SSR" },
  { id: "eternal_frost_bloom", name: "永恒霜花", category: "limited", rarity: "SR" },
  { id: "star_rebirth_orchid", name: "涅槃星兰", category: "limited", rarity: "SR" },
  { id: "clockwork_fern", name: "齿轮蕨", category: "limited", rarity: "SR" },
  { id: "coral_moon_cactus", name: "月珊瑚仙人掌", category: "limited", rarity: "SR" },
  { id: "mirage_thistle", name: "幻景蓟", category: "limited", rarity: "SR" },
  { id: "void_orchid", name: "虚空兰", category: "limited", rarity: "SSR" },
  { id: "dragon_breath_bamboo", name: "龙息竹", category: "limited", rarity: "SSR" },
  { id: "melody_vine", name: "旋律藤", category: "limited", rarity: "SSR" },
  { id: "solar_ember_flower", name: "日烬花", category: "limited", rarity: "SSR" },
  { id: "abyss_bloom", name: "深渊水母花", category: "limited", rarity: "SSR" },
  { id: "origin_vine", name: "始源藤", category: "limited", rarity: "SP" },
  { id: "cosmos_apple_tree", name: "宇宙苹果树", category: "limited", rarity: "SP" },
  { id: "broad_bean", name: "蚕豆", category: "common", rarity: "N" },
  { id: "spring_bamboo_shoot", name: "春笋", category: "common", rarity: "R" },
  { id: "cherry_radish", name: "樱桃萝卜", category: "common", rarity: "N" },
  { id: "loofah", name: "丝瓜", category: "common", rarity: "R" },
  { id: "bitter_melon", name: "苦瓜", category: "common", rarity: "R" },
  { id: "edamame", name: "毛豆", category: "common", rarity: "N" },
  { id: "water_spinach", name: "空心菜", category: "common", rarity: "N" },
  { id: "perilla", name: "紫苏", category: "common", rarity: "R" },
  { id: "chinese_yam", name: "山药", category: "common", rarity: "R" },
  { id: "water_caltrop", name: "菱角", category: "common", rarity: "R" },
  { id: "taro", name: "芋头", category: "common", rarity: "R" },
  { id: "kabocha", name: "栗南瓜", category: "common", rarity: "SR" },
  { id: "napa_cabbage", name: "大白菜", category: "common", rarity: "N" },
  { id: "potherb_mustard", name: "雪里蕻", category: "common", rarity: "R" },
  { id: "tatsoi", name: "塌菜", category: "common", rarity: "N" },
  { id: "stem_mustard", name: "儿菜", category: "common", rarity: "R" },
  { id: "burdock", name: "牛蒡", category: "common", rarity: "R" },
  { id: "arrowhead", name: "慈姑", category: "common", rarity: "R" },
  { id: "winter_bamboo_shoot", name: "冬笋", category: "common", rarity: "SR" },
  { id: "leaf_mustard", name: "芥菜", category: "common", rarity: "N" },
  { id: "rain_bell_bean", name: "雨铃豆", category: "fantasy", rarity: "R" },
  { id: "swallowtail_sprout", name: "燕尾芽", category: "fantasy", rarity: "R" },
  { id: "flower_tide_grass", name: "花信草", category: "fantasy", rarity: "SR" },
  { id: "kite_vine", name: "纸鸢藤", category: "fantasy", rarity: "SR" },
  { id: "spring_thunder_tree", name: "春雷木", category: "fantasy", rarity: "SSR" },
  { id: "firefly_lantern_pepper", name: "萤灯椒", category: "fantasy", rarity: "R" },
  { id: "cicada_bamboo", name: "蝉鸣竹", category: "fantasy", rarity: "SR" },
  { id: "thunderstripe_melon", name: "雷纹瓜", category: "fantasy", rarity: "SR" },
  { id: "tide_lotus", name: "潮汐莲", category: "fantasy", rarity: "SSR" },
  { id: "midsummer_whale_melon", name: "盛夏鲸瓜", category: "fantasy", rarity: "SSR" },
  { id: "amber_grain", name: "琥珀穗", category: "fantasy", rarity: "R" },
  { id: "echo_chestnut", name: "回声栗", category: "fantasy", rarity: "SR" },
  { id: "maple_sugar_root", name: "枫糖根", category: "fantasy", rarity: "SR" },
  { id: "wild_goose_vine", name: "雁信藤", category: "fantasy", rarity: "SR" },
  { id: "moon_dust_taro", name: "月屑芋", category: "fantasy", rarity: "SSR" },
  { id: "snowball_vegetable", name: "雪团菜", category: "fantasy", rarity: "R" },
  { id: "frost_bell_grass", name: "霜铃草", category: "fantasy", rarity: "SR" },
  { id: "ice_candle_flower", name: "冰烛花", category: "fantasy", rarity: "SR" },
  { id: "aurora_moss", name: "极光苔", category: "fantasy", rarity: "SSR" },
  { id: "winter_sleep_fruit", name: "眠冬果", category: "fantasy", rarity: "SSR" },
  { id: "herbarium_page_sprout", name: "百草书芽", category: "limited", rarity: "SR" },
  { id: "four_season_compass_flower", name: "四季罗盘花", category: "limited", rarity: "SSR" },
  { id: "myriad_leaf_chronicle_tree", name: "万叶纪年树", category: "limited", rarity: "SSR" },
  { id: "new_world_seedpod", name: "新世界种荚", category: "limited", rarity: "SP" },
  { id: "star_tide_coral_grass", name: "星潮珊瑚草", category: "limited", rarity: "SR" },
  { id: "amber_pendulum_vine", name: "琥珀钟摆藤", category: "limited", rarity: "SR" },
  { id: "sky_prism_flower", name: "天穹棱镜花", category: "limited", rarity: "SSR" },
  { id: "world_root_crown", name: "世界根冠", category: "limited", rarity: "SP" },
] as const satisfies readonly FarmCropCatalogEntry[];
