export type CookingRecipeCategory = "主食小吃" | "汤羹" | "热菜" | "甜品点心" | "饮品";

export type CookingRecipeRarity = "N" | "R" | "SR" | "SSR" | "SP";

export type CookingIngredientCategoryId =
  | "grains"
  | "produce"
  | "seasoning"
  | "dairy-bean"
  | "sweet-drink";

export interface CookingCatalogIngredient {
  id: string;
  name: string;
  price: number;
  staple: boolean;
  dailyBuyLimit?: number | null;
}

export interface CookingCatalogRecipe {
  id: string;
  name: string;
  rarity: CookingRecipeRarity;
  category: CookingRecipeCategory;
  ingredients: readonly string[];
}

export const COOKING_RECIPE_CATEGORIES: readonly CookingRecipeCategory[] = [
  "主食小吃",
  "汤羹",
  "热菜",
  "甜品点心",
  "饮品",
];

export const COOKING_RECIPE_PRICES: Readonly<Record<CookingRecipeRarity, number>> = {
  N: 30,
  R: 80,
  SR: 200,
  SSR: 500,
  SP: 1200,
};

export const COOKING_CATALOG_INGREDIENTS = [
  {
    id: "salt",
    name: "盐",
    price: 5,
    staple: true,
    dailyBuyLimit: 10,
  },
  {
    id: "flour",
    name: "面粉",
    price: 8,
    staple: true,
    dailyBuyLimit: 10,
  },
  {
    id: "sugar",
    name: "砂糖",
    price: 8,
    staple: true,
    dailyBuyLimit: 10,
  },
  {
    id: "rice",
    name: "大米",
    price: 10,
    staple: true,
    dailyBuyLimit: null,
  },
  {
    id: "soy_sauce",
    name: "酱油",
    price: 10,
    staple: true,
    dailyBuyLimit: 10,
  },
  {
    id: "ginger",
    name: "生姜",
    price: 12,
    staple: true,
    dailyBuyLimit: 10,
  },
  {
    id: "scallion",
    name: "香葱",
    price: 10,
    staple: true,
    dailyBuyLimit: 10,
  },
  {
    id: "onion",
    name: "洋葱",
    price: 8,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "potato",
    name: "马铃薯",
    price: 10,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "corn",
    name: "玉米",
    price: 10,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "carrot",
    name: "胡萝卜",
    price: 10,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "tomato",
    name: "番茄",
    price: 12,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "basil",
    name: "罗勒",
    price: 15,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "pumpkin",
    name: "南瓜",
    price: 18,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "strawberry",
    name: "草莓",
    price: 18,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "tea",
    name: "茶叶",
    price: 18,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "watermelon",
    name: "西瓜",
    price: 20,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "cocoa",
    name: "可可粉",
    price: 22,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "vanilla",
    name: "香草",
    price: 30,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "spice",
    name: "香料",
    price: 35,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "butter",
    name: "黄油",
    price: 20,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "yellow_wine",
    name: "黄酒",
    price: 25,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "tofu",
    name: "豆腐",
    price: 15,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "rainbow_corn",
    name: "彩虹玉米",
    price: 50,
    staple: false,
    dailyBuyLimit: null,
  },
  {
    id: "star_sugar",
    name: "星糖",
    price: 80,
    staple: false,
    dailyBuyLimit: null,
  },
] as const satisfies readonly CookingCatalogIngredient[];

export const COOKING_INGREDIENT_CATEGORIES = [
  {
    id: "grains",
    label: "谷薯",
    ingredientIds: ["flour", "rice", "potato", "corn", "rainbow_corn"],
  },
  {
    id: "produce",
    label: "蔬果",
    ingredientIds: [
      "ginger",
      "scallion",
      "onion",
      "carrot",
      "tomato",
      "basil",
      "pumpkin",
      "strawberry",
      "watermelon",
    ],
  },
  {
    id: "seasoning",
    label: "调味",
    ingredientIds: ["salt", "sugar", "soy_sauce", "spice", "yellow_wine"],
  },
  {
    id: "dairy-bean",
    label: "豆乳",
    ingredientIds: ["butter", "tofu"],
  },
  {
    id: "sweet-drink",
    label: "甜饮",
    ingredientIds: ["tea", "cocoa", "vanilla", "star_sugar"],
  },
] as const satisfies readonly {
  id: CookingIngredientCategoryId;
  label: string;
  ingredientIds: readonly string[];
}[];

export const COOKING_CATALOG_RECIPES = [
  {
    id: "fried_egg",
    name: "香煎蛋",
    rarity: "N",
    category: "热菜",
    ingredients: ["chicken_egg", "salt"],
  },
  {
    id: "tomato_egg",
    name: "番茄炒蛋",
    rarity: "N",
    category: "热菜",
    ingredients: ["chicken_egg", "tomato", "salt"],
  },
  {
    id: "potato_pancake",
    name: "土豆蛋饼",
    rarity: "N",
    category: "主食小吃",
    ingredients: ["chicken_egg", "potato", "flour"],
  },
  {
    id: "corn_custard",
    name: "玉米蛋羹",
    rarity: "N",
    category: "汤羹",
    ingredients: ["chicken_egg", "corn", "salt"],
  },
  {
    id: "carrot_egg",
    name: "胡萝卜煎蛋",
    rarity: "N",
    category: "热菜",
    ingredients: ["chicken_egg", "carrot", "salt"],
  },
  {
    id: "duck_rice_ball",
    name: "鸭蛋饭团",
    rarity: "N",
    category: "主食小吃",
    ingredients: ["duck_egg", "rice", "salt"],
  },
  {
    id: "pumpkin_duck_cup",
    name: "南瓜鸭蛋盅",
    rarity: "N",
    category: "汤羹",
    ingredients: ["duck_egg", "pumpkin", "salt"],
  },
  {
    id: "goose_pancake",
    name: "鹅蛋薄饼",
    rarity: "N",
    category: "主食小吃",
    ingredients: ["goose_egg", "flour", "sugar"],
  },
  {
    id: "basil_chicken_roll",
    name: "罗勒鸡肉卷",
    rarity: "N",
    category: "主食小吃",
    ingredients: ["chicken_meat", "flour", "basil"],
  },
  {
    id: "onion_roast_duck",
    name: "洋葱烤鸭",
    rarity: "N",
    category: "热菜",
    ingredients: ["duck_meat", "onion", "salt"],
  },
  {
    id: "strawberry_milk",
    name: "草莓牛奶",
    rarity: "R",
    category: "饮品",
    ingredients: ["fresh_milk", "strawberry", "sugar"],
  },
  {
    id: "pumpkin_milk_soup",
    name: "南瓜奶汤",
    rarity: "R",
    category: "汤羹",
    ingredients: ["fresh_milk", "pumpkin", "salt"],
  },
  {
    id: "honey_tea",
    name: "蜂蜜茶",
    rarity: "R",
    category: "饮品",
    ingredients: ["honey", "tea"],
  },
  {
    id: "milk_egg_custard",
    name: "奶香蛋羹",
    rarity: "R",
    category: "汤羹",
    ingredients: ["chicken_egg", "fresh_milk", "sugar"],
  },
  {
    id: "honey_strawberry_jelly",
    name: "蜂蜜草莓奶冻",
    rarity: "R",
    category: "甜品点心",
    ingredients: ["fresh_milk", "honey", "strawberry", "sugar"],
  },
  {
    id: "watermelon_milkshake",
    name: "西瓜奶昔",
    rarity: "R",
    category: "饮品",
    ingredients: ["fresh_milk", "watermelon", "sugar"],
  },
  {
    id: "strawberry_cake",
    name: "草莓蛋糕",
    rarity: "R",
    category: "甜品点心",
    ingredients: ["chicken_egg", "strawberry", "flour", "sugar"],
  },
  {
    id: "vanilla_goose_roll",
    name: "香草鹅蛋卷",
    rarity: "R",
    category: "甜品点心",
    ingredients: ["goose_egg", "vanilla", "flour"],
  },
  {
    id: "goose_rice",
    name: "鹅肉炖饭",
    rarity: "R",
    category: "主食小吃",
    ingredients: ["goose_meat", "rice", "onion", "spice"],
  },
  {
    id: "pumpkin_lamb_soup",
    name: "南瓜羊肉汤",
    rarity: "R",
    category: "汤羹",
    ingredients: ["lamb", "pumpkin", "onion", "salt"],
  },
  {
    id: "tomato_beef_stew",
    name: "番茄炖牛肉",
    rarity: "SR",
    category: "热菜",
    ingredients: ["beef", "tomato", "potato", "spice"],
  },
  {
    id: "truffle_omelet_rice",
    name: "松露蛋包饭",
    rarity: "SR",
    category: "主食小吃",
    ingredients: ["truffle", "chicken_egg", "rice", "spice"],
  },
  {
    id: "honey_cocoa_cake",
    name: "蜂蜜可可蛋糕",
    rarity: "SR",
    category: "甜品点心",
    ingredients: ["chicken_egg", "fresh_milk", "honey", "cocoa", "flour"],
  },
  {
    id: "vanilla_goose_cake",
    name: "香草鹅蛋糕",
    rarity: "SR",
    category: "甜品点心",
    ingredients: ["goose_egg", "fresh_milk", "vanilla", "flour"],
  },
  {
    id: "honey_pumpkin_pudding",
    name: "蜂蜜南瓜布丁",
    rarity: "SR",
    category: "甜品点心",
    ingredients: ["chicken_egg", "fresh_milk", "honey", "pumpkin"],
  },
  {
    id: "truffle_steak",
    name: "松露牛排",
    rarity: "SR",
    category: "热菜",
    ingredients: ["beef", "truffle", "spice"],
  },
  {
    id: "honey_roast_duck",
    name: "蜂蜜烤鸭",
    rarity: "SR",
    category: "热菜",
    ingredients: ["duck_meat", "honey", "spice"],
  },
  {
    id: "rainbow_corn_lamb",
    name: "彩虹玉米羊排",
    rarity: "SR",
    category: "热菜",
    ingredients: ["lamb", "rainbow_corn", "spice"],
  },
  {
    id: "warm_souffle",
    name: "暖火舒芙蕾",
    rarity: "SSR",
    category: "甜品点心",
    ingredients: ["warm_egg", "fresh_milk", "vanilla", "flour", "sugar"],
  },
  {
    id: "warm_truffle_egg",
    name: "暖火松露烘蛋",
    rarity: "SSR",
    category: "热菜",
    ingredients: ["warm_egg", "truffle", "spice"],
  },
  {
    id: "warm_strawberry_tart",
    name: "暖火草莓挞",
    rarity: "SSR",
    category: "甜品点心",
    ingredients: ["warm_egg", "fresh_milk", "strawberry", "star_sugar", "flour"],
  },
  {
    id: "star_honey_goose",
    name: "星糖蜜汁烤鹅",
    rarity: "SSR",
    category: "热菜",
    ingredients: ["goose_meat", "honey", "star_sugar", "spice"],
  },
  {
    id: "tea_quail_egg",
    name: "茶香鹌鹑蛋",
    rarity: "N",
    category: "热菜",
    ingredients: ["quail_egg", "tea", "salt"],
  },
  {
    id: "herb_quail_omelet",
    name: "香草鹌鹑蛋饼",
    rarity: "N",
    category: "热菜",
    ingredients: ["quail_egg", "flour", "basil"],
  },
  {
    id: "quail_meat_rice_ball",
    name: "鹌鹑肉饭团",
    rarity: "R",
    category: "主食小吃",
    ingredients: ["quail_meat", "rice", "salt"],
  },
  {
    id: "honey_quail_skewer",
    name: "蜂蜜鹌鹑串",
    rarity: "SR",
    category: "热菜",
    ingredients: ["quail_meat", "honey", "spice"],
  },
  {
    id: "honey_goat_milk",
    name: "蜂蜜羊奶",
    rarity: "R",
    category: "饮品",
    ingredients: ["goat_milk", "honey"],
  },
  {
    id: "strawberry_goat_pudding",
    name: "草莓羊奶布丁",
    rarity: "SR",
    category: "甜品点心",
    ingredients: ["goat_milk", "strawberry", "sugar", "vanilla"],
  },
  {
    id: "potato_goat_stew",
    name: "土豆山羊煲",
    rarity: "R",
    category: "汤羹",
    ingredients: ["goat_meat", "potato", "onion", "salt"],
  },
  {
    id: "spiced_goat_chop",
    name: "香料山羊排",
    rarity: "SR",
    category: "热菜",
    ingredients: ["goat_meat", "tomato", "basil", "spice"],
  },
  {
    id: "turkey_egg_roll",
    name: "火鸡蛋卷",
    rarity: "SR",
    category: "热菜",
    ingredients: ["turkey_egg", "flour", "onion", "salt"],
  },
  {
    id: "pumpkin_turkey_egg_cup",
    name: "南瓜火鸡蛋盅",
    rarity: "SSR",
    category: "汤羹",
    ingredients: ["turkey_egg", "pumpkin", "fresh_milk", "spice"],
  },
  {
    id: "roast_turkey",
    name: "香烤火鸡",
    rarity: "SR",
    category: "热菜",
    ingredients: ["turkey_meat", "potato", "onion", "spice"],
  },
  {
    id: "star_honey_turkey",
    name: "星糖蜜汁火鸡",
    rarity: "SSR",
    category: "热菜",
    ingredients: ["turkey_meat", "honey", "star_sugar", "spice"],
  },
  {
    id: "classic_milk_tea",
    name: "原味奶茶",
    rarity: "R",
    category: "饮品",
    ingredients: ["fresh_milk", "tea", "sugar"],
  },
  {
    id: "strawberry_milk_tea",
    name: "草莓奶茶",
    rarity: "R",
    category: "饮品",
    ingredients: ["fresh_milk", "tea", "strawberry", "sugar"],
  },
  {
    id: "watermelon_milk_tea",
    name: "西瓜奶茶",
    rarity: "R",
    category: "饮品",
    ingredients: ["fresh_milk", "tea", "watermelon", "sugar"],
  },
  {
    id: "honey_milk_tea",
    name: "蜂蜜奶茶",
    rarity: "R",
    category: "饮品",
    ingredients: ["fresh_milk", "tea", "honey"],
  },
  {
    id: "cocoa_milk_tea",
    name: "可可奶茶",
    rarity: "SR",
    category: "饮品",
    ingredients: ["fresh_milk", "tea", "cocoa", "sugar"],
  },
  {
    id: "vanilla_milk_tea",
    name: "香草奶茶",
    rarity: "SR",
    category: "饮品",
    ingredients: ["fresh_milk", "tea", "vanilla", "sugar"],
  },
  {
    id: "star_sugar_milk_tea",
    name: "星糖奶茶",
    rarity: "SSR",
    category: "饮品",
    ingredients: ["fresh_milk", "tea", "star_sugar"],
  },
  {
    id: "tea_egg",
    name: "茶叶蛋",
    rarity: "N",
    category: "热菜",
    ingredients: ["chicken_egg", "tea", "salt"],
  },
  {
    id: "plain_egg_cake",
    name: "鸡蛋糕",
    rarity: "N",
    category: "甜品点心",
    ingredients: ["chicken_egg", "flour", "sugar"],
  },
  {
    id: "honey_egg_cake",
    name: "蜂蜜鸡蛋糕",
    rarity: "R",
    category: "甜品点心",
    ingredients: ["chicken_egg", "flour", "honey", "sugar"],
  },
  {
    id: "cocoa_egg_cake",
    name: "可可鸡蛋糕",
    rarity: "R",
    category: "甜品点心",
    ingredients: ["chicken_egg", "flour", "cocoa", "sugar"],
  },
  {
    id: "pumpkin_egg_cake",
    name: "南瓜鸡蛋糕",
    rarity: "R",
    category: "甜品点心",
    ingredients: ["chicken_egg", "pumpkin", "flour", "sugar"],
  },
  {
    id: "rainbow_corn_egg_cake",
    name: "彩虹玉米鸡蛋糕",
    rarity: "SR",
    category: "甜品点心",
    ingredients: ["chicken_egg", "rainbow_corn", "flour", "sugar"],
  },
  {
    id: "star_sugar_egg_cake",
    name: "星糖鸡蛋糕",
    rarity: "SSR",
    category: "甜品点心",
    ingredients: ["chicken_egg", "star_sugar", "flour", "vanilla"],
  },
  {
    id: "pan_fried_fish",
    name: "香煎鲜鱼",
    rarity: "N",
    category: "热菜",
    ingredients: ["fish:any", "salt"],
  },
  {
    id: "fish_rice_ball",
    name: "鱼肉饭团",
    rarity: "N",
    category: "主食小吃",
    ingredients: ["fish:any", "rice", "salt"],
  },
  {
    id: "tomato_fish_soup",
    name: "番茄鱼汤",
    rarity: "R",
    category: "汤羹",
    ingredients: ["fish:any", "tomato", "onion", "salt"],
  },
  {
    id: "herb_grilled_fish",
    name: "香草烤鱼",
    rarity: "R",
    category: "热菜",
    ingredients: ["fish:any", "basil", "spice"],
  },
  {
    id: "honey_roast_fish",
    name: "蜂蜜烤鱼",
    rarity: "SR",
    category: "热菜",
    ingredients: ["fish:any", "honey", "spice"],
  },
  {
    id: "starlight_fish_feast",
    name: "星河鱼宴",
    rarity: "SSR",
    category: "热菜",
    ingredients: ["fish:any", "star_sugar", "rainbow_corn", "spice"],
  },
  {
    id: "scallion_omelet",
    name: "葱花煎蛋",
    rarity: "N",
    category: "热菜",
    ingredients: ["chicken_egg", "scallion", "salt"],
  },
  {
    id: "scallion_pancake",
    name: "葱油饼",
    rarity: "N",
    category: "主食小吃",
    ingredients: ["flour", "scallion", "salt"],
  },
  {
    id: "butter_fried_egg",
    name: "黄油煎蛋",
    rarity: "N",
    category: "热菜",
    ingredients: ["chicken_egg", "butter", "salt"],
  },
  {
    id: "home_style_tofu",
    name: "家常豆腐",
    rarity: "N",
    category: "热菜",
    ingredients: ["tofu", "soy_sauce", "scallion"],
  },
  {
    id: "butter_corn",
    name: "黄油玉米",
    rarity: "N",
    category: "热菜",
    ingredients: ["corn", "butter", "salt"],
  },
  {
    id: "soy_fried_rice",
    name: "酱油炒饭",
    rarity: "R",
    category: "主食小吃",
    ingredients: ["chicken_egg", "rice", "soy_sauce", "scallion"],
  },
  {
    id: "plain_boiled_chicken",
    name: "白切鸡",
    rarity: "R",
    category: "热菜",
    ingredients: ["chicken_meat", "ginger", "scallion", "salt"],
  },
  {
    id: "red_braised_tofu",
    name: "红烧豆腐",
    rarity: "R",
    category: "热菜",
    ingredients: ["tofu", "soy_sauce", "sugar", "spice"],
  },
  {
    id: "tofu_egg_soup",
    name: "豆腐蛋花汤",
    rarity: "R",
    category: "汤羹",
    ingredients: ["tofu", "chicken_egg", "scallion", "salt"],
  },
  {
    id: "butter_cookie",
    name: "黄油曲奇",
    rarity: "R",
    category: "甜品点心",
    ingredients: ["flour", "butter", "sugar"],
  },
  {
    id: "goat_milk_bun",
    name: "羊奶馒头",
    rarity: "R",
    category: "主食小吃",
    ingredients: ["goat_milk", "flour", "sugar"],
  },
  {
    id: "soy_quail_eggs",
    name: "酱香鹌鹑蛋",
    rarity: "R",
    category: "热菜",
    ingredients: ["quail_egg", "soy_sauce", "sugar", "spice"],
  },
  {
    id: "scallion_oil_chicken",
    name: "葱油鸡",
    rarity: "SR",
    category: "热菜",
    ingredients: ["chicken_meat", "scallion", "ginger", "soy_sauce"],
  },
  {
    id: "ginger_duck",
    name: "姜母鸭",
    rarity: "SR",
    category: "热菜",
    ingredients: ["duck_meat", "ginger", "yellow_wine", "spice"],
  },
  {
    id: "tea_smoked_duck",
    name: "茶香熏鸭",
    rarity: "SR",
    category: "热菜",
    ingredients: ["duck_meat", "tea", "soy_sauce", "spice"],
  },
  {
    id: "red_braised_goose",
    name: "红烧鹅",
    rarity: "SR",
    category: "热菜",
    ingredients: ["goose_meat", "soy_sauce", "sugar", "spice"],
  },
  {
    id: "scallion_lamb",
    name: "葱爆羊肉",
    rarity: "SR",
    category: "热菜",
    ingredients: ["lamb", "scallion", "onion", "soy_sauce"],
  },
  {
    id: "potato_beef",
    name: "土豆烧牛肉",
    rarity: "SR",
    category: "热菜",
    ingredients: ["beef", "potato", "soy_sauce", "spice"],
  },
  {
    id: "yellow_wine_turkey",
    name: "黄酒焖火鸡",
    rarity: "SR",
    category: "热菜",
    ingredients: ["turkey_meat", "yellow_wine", "soy_sauce", "ginger"],
  },
  {
    id: "yellow_wine_quail",
    name: "黄酒焖鹌鹑",
    rarity: "SR",
    category: "热菜",
    ingredients: ["quail_meat", "yellow_wine", "soy_sauce", "ginger"],
  },
  {
    id: "goat_meat_rice",
    name: "山羊肉焖饭",
    rarity: "SR",
    category: "主食小吃",
    ingredients: ["goat_meat", "rice", "soy_sauce", "ginger"],
  },
  {
    id: "truffle_tofu",
    name: "松露豆腐煲",
    rarity: "SR",
    category: "热菜",
    ingredients: ["truffle", "tofu", "soy_sauce", "ginger"],
  },
  {
    id: "red_braised_pork",
    name: "红烧肉",
    rarity: "SR",
    category: "热菜",
    ingredients: ["pork", "soy_sauce", "sugar", "spice"],
  },
  {
    id: "custard_bun",
    name: "奶黄包",
    rarity: "SR",
    category: "甜品点心",
    ingredients: ["chicken_egg", "fresh_milk", "flour", "butter", "sugar"],
  },
  {
    id: "dongpo_pork",
    name: "东坡肉",
    rarity: "SSR",
    category: "热菜",
    ingredients: ["pork", "soy_sauce", "sugar", "yellow_wine", "scallion"],
  },
  {
    id: "truffle_butter_steak",
    name: "松露黄油牛排",
    rarity: "SSR",
    category: "热菜",
    ingredients: ["beef", "truffle", "butter", "spice"],
  },
] as const satisfies readonly CookingCatalogRecipe[];

export const COOKING_INGREDIENT_NAME_BY_ID: Readonly<Record<string, string>> = Object.fromEntries(
  COOKING_CATALOG_INGREDIENTS.map((ingredient) => [ingredient.id, ingredient.name]),
);
