import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './editor.css';
type Reward = { kind: string; amount?: number; id?: string };
type RandomOutcome = {weight:number;text:string;reward:Reward};
type Outcome = { outcomes?:RandomOutcome[]; reward: Reward; cost?: {kind: string; amount: number} };
type Option = Outcome & { label: string; text: string };
type Content = { tools?: string[]; category: string; npcName: string; name: string; type: string; text: string; reward?: Reward; cost?: {kind: string;amount: number}; options?: {A: Option;B: Option} };
type Row = {id:string;version:number;status:string;content:Content};
type Catalog = {tools?:{id:string;name:string}[];item:{id:string;name:string}[];bait:{id:string;name:string}[]};
const labels:Record<string,string> = {none:'无奖励',coins:'金币',silver:'银币',item:'道具',bait:'鱼饵',ingredient:'随机食材 ×1',dish:'随机正常料理 ×1',egg:'随机蛋类产物 ×1',favorite:'动物口味线索'};
const blank = (category='encounter'):Content => ({category,npcName:'',name:'',type:'instant',text:'',reward:{kind:'none'}});
const option = ():Option => ({label:'',text:'',reward:{kind:'none'}});
async function request<T>(body?:unknown):Promise<T>{const response=await fetch('/api/glimmer-editor',{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'content-type':'application/json'}:{},...(body?{body:JSON.stringify(body)}:{})});const value=await response.json();if(!response.ok)throw new Error(value.error?.message??'操作未完成，请重试。');return value;}
function rewardText(reward:Reward,catalog:Catalog){return ['coins','silver'].includes(reward.kind)?`${labels[reward.kind]} +${reward.amount??0}`:['item','bait'].includes(reward.kind)?`${catalog[reward.kind as 'item'|'bait'].find(x=>x.id===reward.id)?.name??'未选择物品'} ×${reward.amount??1}`:labels[reward.kind];}
function Result({value,catalog,onChange,rewardOnly=false}:{value:Outcome;catalog:Catalog;onChange:(value:Outcome)=>void;rewardOnly?:boolean}){
 if(value.outcomes)return <div className="choice"><h3>随机出货表</h3><p className="hint">每次只抽一项，概率合计须为 100%。</p>{value.outcomes.map((entry,index)=><div className="choice" key={index}><label>结果 {index+1} · 概率 %<input type="number" value={entry.weight} onChange={e=>onChange({...value,outcomes:value.outcomes!.map((x,i)=>i===index?{...x,weight:Number(e.target.value)}:x)})}/></label><label>出货剧情<textarea rows={3} value={entry.text} onChange={e=>onChange({...value,outcomes:value.outcomes!.map((x,i)=>i===index?{...x,text:e.target.value}:x)})}/></label><Result rewardOnly value={{reward:entry.reward}} catalog={catalog} onChange={out=>onChange({...value,outcomes:value.outcomes!.map((x,i)=>i===index?{...x,reward:out.reward}:x)})}/></div>)}<label>抽奖扣款<select value={value.cost?.kind??'none'} onChange={e=>onChange({...value,cost:e.target.value==='none'?undefined:{kind:e.target.value,amount:value.cost?.amount??1}})}><option value="none">不扣款</option><option value="coins">金币</option><option value="silver">银币</option></select></label>{value.cost&&<label>扣款数量<input type="number" value={value.cost.amount} onChange={e=>onChange({...value,cost:{...value.cost!,amount:Number(e.target.value)}})}/></label>}</div>;
 const reward=value.reward;
 return <div className="result-fields"><label>奖励<select value={reward.kind} onChange={e=>{const kind=e.target.value;onChange({...value,reward:{kind,...(['coins','silver','item','bait'].includes(kind)?{amount:1}:{}),...(['item','bait'].includes(kind)?{id:catalog[kind as 'item'|'bait'][0]?.id??''}:{})}})}}>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
 {['item','bait'].includes(reward.kind)&&<label>物品<select value={reward.id??''} onChange={e=>onChange({...value,reward:{...reward,id:e.target.value}})}>{catalog[reward.kind as 'item'|'bait'].map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
 {['coins','silver','item','bait'].includes(reward.kind)&&<label>数量<input type="number" min="1" step="1" value={reward.amount??1} onChange={e=>onChange({...value,reward:{...reward,amount:Number(e.target.value)}})}/></label>}
 {!rewardOnly&&<label>扣款<select value={value.cost?.kind??'none'} onChange={e=>{if(e.target.value==='none')onChange({reward});else onChange({reward,cost:{kind:e.target.value,amount:value.cost?.amount??1}})}}><option value="none">不扣款</option><option value="coins">金币</option><option value="silver">银币</option></select></label>}
 {value.cost&&<label>扣款数量<input type="number" min="1" step="1" value={value.cost.amount} onChange={e=>onChange({...value,cost:{kind:value.cost!.kind,amount:Number(e.target.value)}})}/></label>}
 </div>;
}
function Receipt({value,catalog}:{value:Outcome;catalog:Catalog}){if(value.outcomes)return <div>{value.cost&&<p className="receipt">抽奖扣除 {value.cost.amount} {labels[value.cost.kind]}</p>}{value.outcomes.map((entry,i)=><article key={i}><h3>结果 {i+1} · {entry.weight}%</h3><p className="story">{entry.text}</p><Receipt value={{reward:entry.reward}} catalog={catalog}/></article>)}</div>;return <p className="receipt">{value.cost&&<span>扣除 {value.cost.amount} {labels[value.cost.kind]} · </span>}{rewardText(value.reward,catalog)}</p>}
function App(){
 const [importing,setImporting]=useState(false),[importText,setImportText]=useState('');
 const [previewOnly,setPreviewOnly]=useState(false);
 const [rows,setRows]=useState<Row[]>([]),[catalog,setCatalog]=useState<Catalog>({item:[],bait:[]}),[active,setActive]=useState<Row|null>(null),[content,setContent]=useState<Content>(blank()),[status,setStatus]=useState('正在验证访问权限…'),[allowed,setAllowed]=useState(false),[busy,setBusy]=useState(false),[tab,setTab]=useState('encounter'),[preview,setPreview]=useState(false),[dirty,setDirty]=useState(false);
 useEffect(()=>{void request<{entries:Row[];catalog:Catalog;previewOnly?:boolean}>().then(data=>{setPreviewOnly(data.previewOnly===true);setRows(data.entries);setCatalog(data.catalog);setAllowed(true);setStatus('');}).catch(e=>setStatus(e.message));},[]);
 useEffect(()=>{if(preview)document.querySelector('.preview')?.scrollIntoView({behavior:'smooth',block:'start'});},[preview]);
 useEffect(()=>{if(!dirty)return;const stop=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop);},[dirty]);
 const change=(next:Content)=>{setContent(next);setDirty(true);setPreview(false);};
 const open=(row:Row|null,category=tab)=>{if(busy)return;if(dirty&&!window.confirm('当前修改还没有保存，放弃这些修改吗？'))return;setActive(row);setContent(row?structuredClone(row.content):blank(category));setTab(row?.content.category??category);setDirty(false);setPreview(false);setStatus('');};
 const keep=(row:Row)=>{setRows(old=>old.some(x=>x.id===row.id)?old.map(x=>x.id===row.id?row:x):[...old,row]);setActive(row);setContent(row.content);setDirty(false);};
 const save=async()=>{setBusy(true);setStatus('正在保存…');try{const row=await request<Row>({action:'save',...(active?{id:active.id}:{}),version:active?.version??0,content});keep(row);setStatus('草稿已保存。');return row;}catch(e){setStatus((e as Error).message);return null;}finally{setBusy(false);}};
 const publish=async()=>{if(!active||dirty||!preview)return;setBusy(true);setStatus('正在发布…');try{const row=await request<Row>({action:'publish',id:active.id,version:active.version});keep(row);setStatus(previewOnly?'已保存到本地试填库，尚未上架游戏。':content.category==='npc'?'已发布，已加入 NPC 共用内容池。':'已发布，新的探索可以遇见这条内容了。');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}};
 const withdraw=async()=>{if(!active||!window.confirm('撤下后不会再随机触发，已经发出的选项仍可完成。确认撤下吗？'))return;setBusy(true);try{keep(await request<Row>({action:'withdraw',id:active.id,version:active.version}));setPreview(false);setStatus(previewOnly?'已从本地试填池撤下。':'已撤下，不再触发新内容。');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}};
 const review=async()=>{const row=dirty||!active?await save():active;if(!row)return;setBusy(true);try{await request<Row>({action:'review',id:row.id,version:row.version});setPreview(true);setStatus('');}catch(e){setStatus((e as Error).message);setPreview(false);}finally{setBusy(false);}};
 const copy=async(template=false)=>{try{const value=template?{...blank(tab),type:'choice',reward:undefined,...(tab==='npc'?{tools:[]}:{}),options:{A:option(),B:option()}}:content;await navigator.clipboard.writeText(JSON.stringify(value,null,2));setStatus(template?'模板已复制，填写后可粘贴导入。':'当前内容已复制。');}catch{setStatus('复制未成功，请检查浏览器剪贴板权限。');}};
 const importContent=async()=>{if(dirty&&!window.confirm('导入会替换当前未保存的内容，确定继续吗？'))return;setBusy(true);try{let source=importText.trim();if(source.startsWith('```'))source=source.replace(/^```(?:json)?\s*\n/u,'').replace(/\n```$/u,'');let parsed;try{parsed=JSON.parse(source);}catch{throw new Error('格式没有读出来，请粘贴完整的内容模板。');}const next=await request<Content>({action:'import',content:parsed});setActive(null);setContent(next);setTab(next.category);setDirty(true);setPreview(false);setImporting(false);setImportText('');setStatus('已填好表单，请检查后保存和预览发布。');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}};
 const published=active?.status==='published',withdrawn=active?.status==='withdrawn',locked=published||withdrawn;
 const statusLabel=(row:Row)=>row.status==='published'?'已发布':row.status==='withdrawn'?'已撤下':'草稿';
 if(!allowed)return <main className="access"><p className="eyebrow">流光原野</p><h1>内容工作台</h1><p role="status">{status}</p><a href="/">返回社区登录</a></main>;
 return <main className="workbench"><header><a href="/" aria-label="返回社区">←</a><div><p className="eyebrow">流光原野 · 我的创作簿</p><h1>内容工作台</h1></div><span className="owner">仅本人可用</span></header><>{previewOnly&&<p className="hint">本地试填：保存和发布只作用于此预览，不会上架游戏。</p>}</><div className="workspace"><aside><nav aria-label="内容类别">{[['encounter','奇遇'],['npc','NPC 动向']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{if(tab!==id)open(null,id);}}>{label}</button>)}</nav><button className="new" onClick={()=>open(null)}>＋ 新增{tab==='npc'?'动向':'奇遇'}</button><div className="entries">{rows.filter(row=>row.content.category===tab).map(row=><button key={row.id} aria-current={active?.id===row.id?'true':undefined} onClick={()=>open(row)}><strong>{row.content.name||'未命名草稿'}</strong><small>{statusLabel(row)}</small></button>)}{!rows.some(row=>row.content.category===tab)&&<p className="quiet">还没有创作，从一条小故事开始。</p>}</div></aside><section className="sheet"><div className="sheet-head"><h2>{active?content.name||'未命名草稿':tab==='npc'?'新增 NPC 动向':'新增奇遇'}</h2><span>{locked?statusLabel(active!):dirty?'尚未保存':'草稿'}</span></div>
 <div className="actions"><button disabled={busy} onClick={()=>void copy(true)}>复制模板</button><button disabled={busy} onClick={()=>void copy()}>复制当前内容</button><button disabled={busy} onClick={()=>setImporting(!importing)}>粘贴填表</button></div>{importing&&<div><label>粘贴内容模板<textarea rows={8} value={importText} onChange={e=>setImportText(e.target.value)} placeholder="把复制的完整内容粘贴到这里"/></label><button disabled={busy||!importText.trim()} onClick={()=>void importContent()}>填入表单</button><button disabled={busy} onClick={()=>setImporting(false)}>取消导入</button><p className="hint">导入为一条新草稿，不会自动保存或发布。</p></div>}
 <fieldset disabled={busy||locked}><label>标题<input value={content.name} onChange={e=>change({...content,name:e.target.value})} placeholder="给这次相遇起个名字"/></label>{tab==='npc'&&<label>NPC 名字<input value={content.npcName} onChange={e=>change({...content,npcName:e.target.value})}/></label>}
 {tab==='npc'&&<div className="motion-settings"><p className="hint">附在所选工具的正常回执后面。与现有 NPC 共用 20% 触发机会，触发后从符合条件的内容中等概率选一条。</p><details open><summary>触发工具 · 已选 {content.tools?.length??0} 个</summary><div className="tool-list">{(catalog.tools??[]).map(tool=><label key={tool.id}><input type="checkbox" checked={content.tools?.includes(tool.id)??false} onChange={e=>change({...content,tools:e.target.checked?[...(content.tools??[]),tool.id]:(content.tools??[]).filter(id=>id!==tool.id)})}/><span><strong>{tool.id}</strong><small>{tool.name}</small></span></label>)}</div></details></div>}
 <label>触发方式<select value={content.type} onChange={e=>{if(!window.confirm('切换触发方式会清空当前奖励、扣款和选项。取消可保留内容，确定切换吗？'))return;const {reward,cost,options,...rest}=content;change({...rest,type:e.target.value,...(e.target.value==='choice'?{options:{A:option(),B:option()}}:{reward:{kind:'none'}})});}}><option value="instant">直接触发</option><option value="choice">选择 A / B</option></select></label>
 <label>剧情<textarea rows={5} value={content.text} onChange={e=>change({...content,text:e.target.value})} placeholder={tab==='npc'?'写下要附在工具回执里的内容…':'写下小机探索时会看到的内容…'}/></label>
 {content.type==='instant'?<Result value={{reward:content.reward??{kind:'none'},...(content.cost?{cost:content.cost}:{})}} catalog={catalog} onChange={out=>{const {reward,cost,...rest}=content;change({...rest,...out});}}/>:(['A','B'] as const).map(key=>{const item=content.options![key];return <div className="choice" key={key}><h3>选项 {key}</h3><label>选项文字<input value={item.label} onChange={e=>change({...content,options:{...content.options!,[key]:{...item,label:e.target.value}}})}/></label><label>选择后的剧情<textarea rows={3} value={item.text} onChange={e=>change({...content,options:{...content.options!,[key]:{...item,text:e.target.value}}})}/></label><Result value={item} catalog={catalog} onChange={out=>change({...content,options:{...content.options!,[key]:{label:item.label,text:item.text,...out}}})}/></div>})}
 </fieldset><p className="hint">奖励和扣款以表单数值为准，剧情里的金额请保持一致。{content.type==='choice'?'付费选项余额不足时不扣款，可以重新选择。':'直接扣款最多扣到 0，不欠债。'}</p>
 <div className="actions">{locked?<><button disabled={busy} onClick={()=>{setActive(null);setContent(structuredClone(content));setDirty(true);setPreview(false);setStatus('已复制，可以修改后保存为新内容。');}}>复制新建</button>{published?<button disabled={busy} onClick={()=>void withdraw()}>撤下内容</button>:<button disabled={busy} onClick={()=>void review()}>预览恢复</button>}</>:<><button disabled={busy} onClick={()=>void save()}>保存草稿</button><button disabled={busy} onClick={()=>void review()}>预览发布</button></>}</div><p className="status" role="status">{status}</p>
 </section>{preview&&active&&!published&&<section className="preview" aria-label="发布预览"><p className="eyebrow">发布前，再读一遍</p><h2>{content.name}</h2><p className="story">{content.category==='npc'?`〔${content.npcName}〕${content.text}`:content.text}</p>{content.type==='instant'?<Receipt value={{reward:content.reward!,...(content.cost?{cost:content.cost}:{})}} catalog={catalog}/>:(['A','B'] as const).map(key=><article key={key}><h3>{key} · {content.options![key].label}</h3><p className="story">{content.options![key].text}</p><Receipt value={content.options![key]} catalog={catalog}/></article>)}<p className="hint">{content.category==='npc'?`发布后在所选 ${content.tools?.length??0} 个工具的回执中，与现有 NPC 共用 20% 触发机会。`:'发布后加入探索内容池。已经触发的其他奇遇保持不变。'}</p>{content.category==='npc'&&<div><h3>触发工具</h3><ul>{(content.tools??[]).map(id=><li key={id}><strong>{id}</strong><p>{catalog.tools?.find(tool=>tool.id===id)?.name??id}</p></li>)}</ul></div>}<button className="publish" disabled={busy||dirty} onClick={()=>void publish()}>{withdrawn?'确认恢复发布':'确认发布'}</button><button disabled={busy} onClick={()=>setPreview(false)}>继续修改</button></section>}</div></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
